'use client';
import { useTheme } from '@/context/ThemeContext';
import { useRouter } from 'next/navigation';
import { F } from '@/components/ui/primitives';

export default function TermsPage() {
  const { theme: T } = useTheme();
  const router = useRouter();
  const sections = [
    { title: '1. Acceptance of Terms', body: 'By using MonetStudy, you agree to these Terms of Service. If you do not agree, please do not use the platform.' },
    { title: '2. User Content', body: 'You are solely responsible for the content you upload and share. By making a course public, you confirm you have the right to share that content and that it does not infringe any third-party intellectual property rights.' },
    { title: '3. Copyright Policy', body: 'MonetStudy respects intellectual property rights. If you believe content on our platform infringes your copyright, please report it using the flag button on the course. We will review and remove infringing content within 48 hours.' },
    { title: '4. AI-Generated Content', body: 'Courses on MonetStudy are generated by AI based on user-provided material. The AI synthesizes and rephrases content — it does not copy verbatim. However, users are still responsible for ensuring their source material is legally shareable.' },
    { title: '5. Payments', body: 'All payments are one-time and non-refundable unless the service was not delivered. Payments are processed securely by Pesapal.' },
    { title: '6. Account Termination', body: 'We reserve the right to suspend or terminate accounts that repeatedly violate these terms, including uploading infringing content.' },
    { title: '7. Changes to Terms', body: 'We may update these terms at any time. Continued use of MonetStudy after changes means you accept the new terms.' },
    { title: '8. Contact', body: 'For any questions or copyright claims, contact us at neithenbrooke@gmail.com.' },
  ];
  return (
    <div style={{ minHeight: '100vh', background: T.bg, padding: '24px 20px', maxWidth: 600, margin: '0 auto' }}>
      <button onClick={() => router.back()} style={{ background: T.card2, border: `1px solid ${T.border}`, color: T.text, padding: '7px 14px', borderRadius: 8, fontSize: 13, fontFamily: F.sans, cursor: 'pointer', marginBottom: 24 }}>← Back</button>
      <h1 style={{ fontSize: 24, fontWeight: 700, color: T.text, fontFamily: F.sans, marginBottom: 6 }}>Terms of Service</h1>
      <p style={{ fontSize: 13, color: T.muted, fontFamily: F.sans, marginBottom: 32 }}>Last updated: March 2026</p>
      {sections.map((s, i) => (
        <div key={i} style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 15, fontWeight: 700, color: T.text, fontFamily: F.sans, marginBottom: 8 }}>{s.title}</h2>
          <p style={{ fontSize: 14, color: T.textSub, fontFamily: F.sans, lineHeight: 1.8 }}>{s.body}</p>
        </div>
      ))}
    </div>
  );
}
